### ISSUE TITLE
the timestamp doesn't match?

### ISSUE THREAD

**Issue by j5207** [cmusphinx/pocketsphinx-python#43]
HI,
When I print out the first/end frame of each word, I found out that the time stamp is not matching, not even close. The audio file is 410s while the last word's end frame is nearly 3000s. I use the default configuration with decoder and divide the each frame with 100.
Could anybody inform me why this is happening?

**Comment by dhdaines** [comment]
This is because for some reason -remove_silence and -remove_noise are enabled by default in the pocketsphinx configuration.  This makes it drop silence and noise frames, so the frame indices only correspond to actual speech.  It speeds up decoding but confuses everybody!  You can fix it like this:

```
cfg = pocketsphinx.Decoder.get_default_config()
cfg.set_boolean('-remove_silence', False)
cfg.set_boolean('-remove_noise', False)
decoder = pocketsphinx.Decoder(cfg)
```

etc.

**Comment by nshmyrev** [comment]
Hi @dhdaines 

remove_noise should be almost always enabled because models are trained with noise removal feature.

remove_silence is also a very good thing because it allows to properly compute CMN estimate, thus much better accuracy.

The current proposal is to use continuous processing, then timing will be correct. The implementation of continuous processing is not great though.

**Comment by dhdaines** [comment]
If you use continuous processing, doesn't this prevent you from getting whole-utterance CMN, though?

**Comment by dhdaines** [comment]
I suppose that is only relevant if you're doing offline recognition, of course...

**Comment by nshmyrev** [comment]
Whole utterance cmn is also ok, and still CMN estimation is best without silence frames which could be really long in real life (2 seconds of silence around short command) unlike in common ASR databases. Thats what remove_silence is doing and this is why it is enabled by default.

Timing and whole-utterance processing are not very easy, it is correct.

**Comment by ToxicSam** [comment]
Hi, is there a way to get the starting and ending time-step of each phoneme. I am still a little bit confused by that.

**Comment by dhdaines** [comment]
Hi,

There isn't a particularly easy way to do that at the moment.  The search
is word-based (otherwise it would be horribly slow) - if you use allphone
decoding you will get phone segmentations but the phoneme accuracy isn't
very good.

The intention is that state align search can be used as a second pass to
get phone alignments.  (in fact, it will give them to you, but this
involves writing code)  I am trying to find some time to implement this.

**Comment by ToxicSam** [comment]
> Hi, There isn't a particularly easy way to do that at the moment. The search is word-based (otherwise it would be horribly slow) - if you use allphone decoding you will get phone segmentations but the phoneme accuracy isn't very good. The intention is that state align search can be used as a second pass to get phone alignments. (in fact, it will give them to you, but this involves writing code) I am trying to find some time to implement this.
> […](#)

Thank you for your reply! I still wondering does continuous processing approximate the time steps?

**Comment by lenzo-ka** [comment]
This module is obsolete; python bindings are now in [pocketsphinx](https://github.com/cmusphinx/pocketsphinx)
